#!/usr/bin/env bash

root=$(pwd)
build_dir="$root/build"
src_dir="$root/src/mnkgame"

function usage {
  cat <<HELP_USAGE
usage: $0 [options]

Script created to compile the source files.

options:
  -h, --help                    show this help message and exit
  -c, --clean                   delete the "build" folder
  -b, --build                   build the "src" folder
  -rb, --rebuild                executes in succession: -c and -b commands
HELP_USAGE
}

function build {
  files=$(find $src_dir -name "*.java")
  echo $(javac -cp $src_dir -d build $files)
}

function clean {
  echo $(rm -rf $build_dir)
}

function rebuild {
  clean
  build
}

function main {
  case $1 in
    "-c" | "--clean") clean ;;
    "-b" | "--build") build ;;
    "-rb" | "--rebuild") rebuild ;;
    "-h" | "--help" | *) usage ;;
  esac

  exit 0
}

main "$@"
